base_dir: 'CMB-Mock-Data/'
cosmopower_path: '/Users/harry/Documents/Software/cosmopower'
lcut: 0 # integer minimum l to consider
seed: 42

mock_data:
  params: [0.022, 0.12, 0.96, 3.0448, 0.674]

prior:
  name: 'narrow_cosmopower_prior'

joint_likelihood:
  flag: False

polychord:
  ndims: 5
  nderived: 0
  resume: False

nre:
  retrain: True
  nsamples: 50000
  load_data: True # whether or not to use precalcualted data
  lr: 1e-4
  nhidden: [25, 25, 25, 25, 25]
  activation: 'sigmoid'