base_dir: 'CMB-Mock-Data-conservative-prior/'
cosmopower_path: '/Users/harrybevins/Documents/Software/cosmopower'
lcut: null # integer minimum l to consider
seed: 42

mock_data:
  params: [0.022, 0.12, 0.96, 3.0448, 0.674]

prior:
  name: 'conservative_prior'

joint_likelihood:
  flag: False

polychord:
  ndims: 5
  nderived: 0
  resume: True

nre:
  retrain: True
  nsamples: 50000
  load_data: False # whether or not to use precalcualted data
  lr: 1e-4
  nhidden: [25, 25, 25, 25, 25]
  activation: 'sigmoid'